{{- if .Values.notifyPush.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.notifyPush.fullname" . }}
  labels:
    {{- include "nextcloud.notifyPush.labels" . | nindent 4 }}
    {{- with .Values.notifyPush.deploymentLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.notifyPush.deploymenAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.notifyPush.replicaCount }}
  strategy:
    {{ toYaml .Values.notifyPush.strategy | indent 4 }}
  selector:
    matchLabels:
      {{ include "nextcloud.notifyPush.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "nextcloud.notifyPush.selectorLabels" . | nindent 8 }}
      annotations:
        nextcloud-config-hash: {{ include "nextcloud.configHash" . }}
        {{- with .Values.notifyPush.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with pluck "pullSecrets" .Values.image .Values.notifyPush.image }}
      imagePullSecrets:
      {{ range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if or .Values.notifyPush.checkBin.enabled .Values.notifyPush.extraInitContainers }}
      initContainers:
      {{- if .Values.notifyPush.checkBin.enabled }}
      - name: notify-push-install
        image: "{{ .Values.notifyPush.checkBin.image.repository | default .Values.image.repository }}:{{ .Values.notifyPush.checkBin.image.tag | default .Values.image.tag }}"
        imagePullPolicy: {{ .Values.notifyPush.checkBin.image.pullPolicy | default .Values.image.pullPolicy }}
        env:
        {{ include "nextcloud.envs" . | nindent 8 }} {{/*- defined in "_envs.tpl" */}}
        command:
        - /bin/bash
        - -c
        - |
          until [ -f "${NOTIFY_PUSH_BIN:-/var/www/html/custom_apps/notify_push/bin/$(uname -m)/notify_push}" ]; do
            echo "Binary not present yet. Waiting..."
            sleep 2
          done;
        volumeMounts:
        {{- include "nextcloud.volumeMounts.common" . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: notify-push
        image: "{{ .Values.notifyPush.image.repository | default .Values.image.repository }}:{{ .Values.notifyPush.image.tag | default .Values.image.tag }}"
        imagePullPolicy: {{ .Values.notifyPush.image.pullPolicy | default .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - "exec ${NOTIFY_PUSH_BIN:-/var/www/html/custom_apps/notify_push/bin/$(uname -m)/notify_push} /var/www/html/config/config.php"
        {{- with .Values.notifyPush.lifecycle }}
        lifecycle:
          {{- with .postStartCommand }}
          postStart:
            exec:
              command:
                {{ toYaml . | nindent 16 -}}
          {{- end }}
          {{- with .preStopCommand }}
          preStop:
            exec:
              command:
                {{- toYaml . | nindent 16 -}}
          {{- end }}
        {{- end }}
        env:
        - name: PORT
          value: {{ .Values.notifyPush.containerPort|quote }}
        - name: NEXTCLOUD_URL
          value: "{{ .Values.notifyPush.nextcloudURL | default (include "nextcloud.url" .) }}"
        {{- with .Values.notifyPush.extraEnv }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.notifyPush.containerPort }}
          protocol: TCP
        {{- with .Values.notifyPush.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.notifyPush.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.notifyPush.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.notifyPush.resources }}
        resource:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- include "nextcloud.volumeMounts.common" . | nindent 8 }}
      volumes:
      {{- include "nextcloud.volumes" . | nindent 6 }}
      securityContext:
        {{- (include "nextcloud.securityContext.nonRoot" (list . .Values.notifyPush.securityContext)) | nindent 8 }}
      {{- include "nextcloud.notifyPush.affinity" . | nindent 6 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.rbac.serviceaccount.name }}
      {{- end }}
{{- end }}
