{{- if and .Values.notifyPush.enabled .Values.notifyPush.appInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "nextcloud.notifyPush.appInstall.fullname" . }}
  labels:
    {{- include "nextcloud.notifyPush.labels" . | nindent 4 }}
    {{- with .Values.notifyPush.appInstall.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.notifyPush.appInstall.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      {{- with pluck "pullSecrets" .Values.image .Values.notifyPush.image }}
      imagePullSecrets:
      {{ range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: {{ .Values.notifyPush.appInstall.restartPolicy }}
      containers:
      - name: notify-push-install
        image: "{{ .Values.notifyPush.appInstall.image.repository | default .Values.image.repository }}:{{ .Values.notifyPush.appInstall.image.tag | default .Values.image.tag }}"
        imagePullPolicy: {{ .Values.notifyPush.appInstall.image.pullPolicy | default .Values.image.pullPolicy }}
        env:
        {{ include "nextcloud.envs" . | nindent 8 }} {{/*- defined in "_envs.tpl" */}}
        command:
        - /bin/bash
        - -c
        - |
          if [ ! -f "/var/www/html/custom_apps/notify_push/bin/x86_64/notify_push" ]; then
            until [ -f "/var/www/html/config/config.php" ]; do
              echo "Waiting config to appear..."
              sleep 2
            done;
            until ./occ app:list | grep notify_push; do
              echo "notify_push app not found. Installing..."
              ./occ app:install notify_push
            done;
          fi
        {{- with .Values.notifyPush.appInstall.extraEnv }}
        env:
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.notifyPush.appInstall.resources }}
        resource:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- include "nextcloud.volumeMounts.common" . | nindent 8 }}
      volumes:
      {{- include "nextcloud.volumes" . | nindent 8 }}
      securityContext:
        {{- (include "nextcloud.securityContext.nonRoot" (list . .Values.notifyPush.securityContext)) | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.notifyPush.appInstall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.rbac.serviceaccount.name }}
      {{- end }}
{{- end }}
